version: '3'

services:
  database:
    container_name: database
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: neymar
      MYSQL_DATABASE: main
      MYSQL_USER: neymar
      MYSQL_PASSWORD: neymar
    ports:
      - 3306:3306


  phpadmin:
    container_name: phpadmin
    image: phpmyadmin
    restart: always
    ports:
    - 8080:80
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: neymar
      PMA_PASSWORD: neymar

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
